### PR TITLE
Added a default case to ConstructorInjectionPoint

### PR DESCRIPTION
**Pull request by bysse**
I've added a default case to ConstructorInjectionPoint so that it doesn't fail silently if someone should happen to use more than ten arguments to a class.

### CODE REVIEW

**Comment by creynders** [comment]
Anybody who uses more than 10 constructor arguments deserves a silent fail ;)

**Comment by tschneidereit** [comment]
Yup, this makes a lot of sense. One might deserve a fail for using more than 10 args, but a silent fail is just mean. :)

> why you can't add more cases?

Why would we? Really, you shouldn't use that many args for your ctors. Ever.

**Comment by bysse** [comment]
Great, thanks!

**Comment by vlaaad** [comment]
I don't use that many args, but 10 args limitation looks strange.

**Comment by tschneidereit** [comment]
> Great, thanks!

Thank you for the patch!

> I don't use that many args, but 10 args limitation looks strange.

There's no way to support an unlimited number of args, so we have to
draw the line somewhere. Would 11 or 12 look less strange?

**Pull request merged**
